version: '3.1'
services:
  mavenwebapp:
    image: dockerpvp/mavenwebapp:TAG
    ports:
    - 8080:8080
    networks:
    - custombridge
    volumes:
    - ubuntu_MongoVol_EBS-pvp
   
networks:
  custombridge:
    external: true
    
volumes:
  ubuntu_MongoVol_EBS-pvp:
    external: true
