version: '3.1'
services:
  mavenwebapp:
    image: dockerpvp/dockerpvp/mavenwebapp:TAG
    ports:
    - 8080:8080
    networks:
    - custombridge
    volumes:
    - TestVol
networks:
  custombridge:
    external: true
volumes:
  TestVol:
    external: true
