apiVersion: v1
kind: Pod

metadata:
  name: mavenwebapp-pod
  namespace: dev-ns
  labels:
    app: mvn

spec:
  containers:
   - name: mavenwebapp-cont
     image: dockerpvp/mavenproject:${env.BUILD_NUMBER}
     ports:
     - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: mavenwebapp-svc  
  namespace: dev-ns
spec:
  type: NodePort
  selector:
    app: mvn
  ports:
  - port: 80
    targetPort: 8080
